backend:
  name: github
  repo: sarpisik/sarpel-web
  branch: dev
  base_url: https://l4oswclvq4.execute-api.eu-central-1.amazonaws.com
  auth_endpoint: /prod/github/auth
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'
  # Enable for local development.
  # Run: npx netlify-cms-proxy-server
  # local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: 'project'
    label: 'Projeler'
    folder: 'src/pages/projeler'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'project-page'
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Featured Post', name: 'featuredpost', widget: 'boolean' }
      - { label: 'Featured Image', name: 'featuredimage', widget: image }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page'
            }
          - {
              label: Bannerlar,
              name: banners,
              widget: list,
              fields:
                [
                  { label: Resim, name: image, widget: image },
                  { label: Metin, name: text, widget: string }
                ]
            }
          - {
              label: Faaliyet Alanlarımız,
              name: whatWeDo,
              widget: object,
              fields:
                [
                  { label: Başlık, name: title, widget: string },
                  {
                    label: Faaliyetler,
                    name: works,
                    widget: list,
                    fields:
                      [
                        { label: Başlık, name: title, widget: string },
                        { label: Açıklama, name: description, widget: text },
                        { label: Resim, name: image, widget: image }
                      ]
                  }
                ]
            }
          - {
              label: Neden Biz?,
              name: whyUs,
              widget: object,
              fields:
                [
                  { label: Başlık, name: title, widget: string },
                  {
                    label: Faktörler,
                    name: reasons,
                    widget: list,
                    fields:
                      [
                        { label: Başlık, name: title, widget: string },
                        { label: Açıklama, name: description, widget: text },
                        { label: Ikon, name: icon, widget: string }
                      ]
                  }
                ]
            }
      - file: 'src/pages/kurumsal/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page'
            }
          - { label: 'Başlık', name: 'title', widget: 'string' }
          - {
              label: 'Banner',
              name: 'banner',
              widget: 'object',
              fields:
                [
                  { label: Resim, name: image, widget: image },
                  { label: Alt, name: alt, widget: string }
                ]
            }
          - { label: 'İçerik', name: 'body', widget: 'markdown' }